### ISSUE TITLE
CI 실행 중 에러 발생

### ISSUE THREAD

**Issue by junghoon-vans** [SHSongs/cheese-shop#25]
![스크린샷 2023-09-22 오후 10 22 49](https://github.com/SHSongs/cheese-shop/assets/44942700/bb96ce4f-be0e-4672-8327-daeeb8ee417c)

해당 이슈는 [Sbt Dependency Submission](https://github.com/marketplace/actions/sbt-dependency-submission)이 write 권한이 없어 발생합니다.

**Comment by darkenpeng** [comment]
👍

**Comment by hatchling13** [comment]
👍
